//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SImpleWebApp.Models
{
    using System;
    using System.Collections.Generic;


    public partial class T_products
    {
      
        public int P_id { get; set; }
        public string P_name { get; set; }
        public string P_description { get; set; }
        public int P_stock { get; set; }
    }
}
